name: Deploy

on:
  workflow_run:
    workflows: [test] # Triggered by the test workflow
    types: [completed] # The test workflow must complete
    branches: [assignment10] # Only when main is updated

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only when test completed successfully
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build React application
        run: npm run build

      - name: Package application
        run: zip -r "app_deploy-${{ github.sha }}.zip" . -x "node_modules/*" -x "*.log"

      - name: Upload application artifact
        uses: actions/upload-artifact@v3
        with:
          name: app_application_artifact
          path: app_deploy-${{ github.sha }}.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Upload application file to AWS
        run: aws s3 cp app_deploy-${{ github.sha }}.zip s3://yourappbucket

      - name: Create new application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name yourapp \
          --source-bundle S3Bucket="flaskbbapp",S3Key="app_deploy-${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy application
        run: aws elasticbeanstalk update-environment --environment-name flaskbb-environment --version-label "ver-${{ github.sha }}"
